version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - leetcode-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:7-alpine
    networks:
      - leetcode-network
    deploy:
      replicas: 1

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=leetcode_db
      - POSTGRES_MULTIPLE_DATABASES=keycloak
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - leetcode-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  server:
    image: scd-leetcode_server:latest
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/leetcode_db
      - RUNNER_URL=http://traefik:80/execute
      - REDIS_URL=redis://redis:6379/0
    networks:
      - leetcode-network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.server.rule=PathPrefix(`/api`)"
        - "traefik.http.services.server.loadbalancer.server.port=5001"

  # Code Execution Workers
  runner:
    image: scd-leetcode_runner:latest
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
    networks:
      - leetcode-network
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.runner.rule=PathPrefix(`/execute`)"
        - "traefik.http.services.runner.loadbalancer.server.port=5000"
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_HOSTNAME_URL: http://localhost:8081
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - leetcode-network
    deploy:
      replicas: 1

  client:
    image: scd-leetcode_client:latest
    networks:
      - leetcode-network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.client.rule=PathPrefix(`/`)"
        - "traefik.http.services.client.loadbalancer.server.port=3000"

networks:
  leetcode-network:
    driver: overlay

volumes:
  db_data:
